# Generated by Django 4.1.7 on 2023-04-13 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_remove_user_user_type_user_is_hod_user_is_student_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
