# Generated by Django 4.1.7 on 2023-04-17 18:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_hod', '0002_course_student_delete_courses'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='date_of_birth',
            new_name='dob',
        ),
        migrations.RemoveField(
            model_name='course',
            name='code',
        ),
    ]
