# Generated by Django 4.1.7 on 2023-04-17 18:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_hod', '0003_rename_date_of_birth_student_dob_remove_course_code'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='title',
            new_name='name',
        ),
    ]
